# Generated by Django 4.2.7 on 2023-11-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBudget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
